version = 0.1

[default.deploy.parameters]
stack_name = "caredata-api"
resolve_s3 = true
s3_prefix = "caredata-api"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-2"
